### ISSUE TITLE
Evaluate localservice.host

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerLabs/code-sample-editor#13]

**Comment by EricSimons** [comment]
Hi all! Happy to answer any q's about localservice. Here's the todo list from my chat with @e111077 & @justinfagnani yesterday:

- [ ] Expose API for resolving requests inside web workers.
- [ ] Allow user to provide self hosted URL as config option (i.e. make CDN optional).
- [ ] Automatically clean up (aka `unregister`) localservice SW's on client disconnect.
(This makes spinning up multiple SW's less of an issue, bc they get destroyed immediately after use)

^ Planning to knock these out by EOW- lmk if I missed anything!

**Comment by e111077** [comment]
Stateless SW rejected in favor of stateful for performance reasons
